### ISSUE TITLE
HELP fixing the error

### ISSUE THREAD

**Issue by AriaFantom** [lorencerri/quick.db#161]
(node:3557) UnhandledPromiseRejectionWarning: TypeError: db.startsWith is not a function
Getting this error on glitch hosting 
Discord.js version  11.5
Quick.db version 7.1.1
Node version 12.x

**Comment by INEX07** [comment]
@Priyanshu348 use `db.all()` method

**Comment by DaemonBeast** [comment]
Linked to issue https://github.com/plexidev/quick.db/issues/170.
