### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by LewisTR** [lorencerri/quick.db#165]
GoProstrtr44@endbot:/mnt/project/app$ npm i quick.db

> integer@1.0.7 install /mnt/project/app/node_modules/integer
> node-gyp rebuild

make: Entering directory '/mnt/project/app/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp: In static member function ‘static Result Integer::Cast(v8::Local<v8::String>, uint8_t)’:
../src/integer.cpp:329:33: error: no matching function for call to ‘v8::String::Value::Value(v8::Local<v8::String>&)’
   v8::String::Value utf16(string);
                                 ^
In file included from /mnt/user/.cache/node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/mnt/user/.cache/node-gyp/12.13.1/include/node/v8.h:3062:5: note: candidate: v8::String::Value::Value(v8::Isolate*, v8::Local<v8::Value>)
     Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~
/mnt/user/.cache/node-gyp/12.13.1/include/node/v8.h:3062:5: note:   candidate expects 2 arguments, 1 provided
integer.target.mk:112: recipe for target 'Release/obj.target/integer/src/integer.o' failed
make: *** [Release/obj.target/integer/src/integer.o] Error 1
make: Leaving directory '/mnt/project/app/node_modules/integer/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-62-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/project/app/node_modules/integer
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /mnt/user/.npm/_logs/2020-06-12T20_51_32_609Z-debug.log

**Comment by danielpmc** [comment]
Same problem here. Quick.db wants a old version of integer for some reason.

**Comment by demonslayer486** [comment]
I'm having the same problem. I think they need to fix it soon. :(

**Comment by Helixable** [comment]
Re-installing node fixed all problems like this for me.

**Comment by MooseFlip** [comment]
yes same problem, will try @Helixable 's answer.
will notify if it works.
