### ISSUE TITLE
.startsWith function added back

### ISSUE THREAD

**Issue by Conutik** [lorencerri/quick.db#170]
**Is your feature request related to a problem? Please describe.**
Yes, I have been trying to find a way to add a leaderboard.

**Describe the solution you'd like**
Readd the .startsWith() function

**Describe alternatives you've considered**
Searching google for an alternative but all I got was to loop the guild members.

**Additional context**
None

**Comment by Helixable** [comment]
@Conutik 
```javascript
if (!String.prototype.startsWith) {
    Object.defineProperty(String.prototype, 'startsWith', {
        value: function(search, rawPos) {
            var pos = rawPos > 0 ? rawPos|0 : 0;
            return this.substring(pos, pos + search.length) === search;
        }
    });
}
```

Try that. It's a polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by Conutik** [comment]
I dont understand hhow to use it

**Comment by Conutik** [comment]
> @Conutik
> 
> ```js
> if (!String.prototype.startsWith) {
>     Object.defineProperty(String.prototype, 'startsWith', {
>         value: function(search, rawPos) {
>             var pos = rawPos > 0 ? rawPos|0 : 0;
>             return this.substring(pos, pos + search.length) === search;
>         }
>     });
> }
> ```
> 
> Try that. It's a polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by Helixable** [comment]
In basic terms, copy and paste it in your main file, or before wherever you need to use `.startsWith()`.

**Comment by Conutik** [comment]
ok

**Comment by Conutik** [comment]
`const { MessageEmbed } = require("discord.js")
const { cyan } = require("../../colours.json");
const db = require('quick.db');

module.exports = { 
    config: {
        name: "top",
        description: "Test The Bot",
        usage: "To annoy kiddoz who want to ping me",
        category: "miscellaneous",
        accessableby: "Members"
    },
    run: async (bot, message, args) => {

    let money = db.startsWith(`scores_${message.guild.id}`, { sort: '.data'})
    let content = "";

    if (!String.prototype.startsWith) {
    Object.defineProperty(String.prototype, 'startsWith', {
        value: function(search, rawPos) {
            var pos = rawPos > 0 ? rawPos|0 : 0;
            return this.substring(pos, pos + search.length) === search;
        }
    });
}

    for (let i = 0; i < 10; i++) {
        let user = bot.users.get(scores[i].ID.split('_')[2]).username

      

        content += `${i+1}. ${user} ~ ${money[i].data}\n`
    
      }

      const embed = new MessageEmbed()
    .setDescription(`**${message.guild.name}'s Coin Leaderboard**\n\n${content}`)
    .setColor("#FFFFFF")

    message.channel.send(embed)
    }
}`

**Comment by Conutik** [comment]
Like this?

**Comment by Helixable** [comment]
No omg. You need to have a basic understanding of JS before asking for help here.

**Comment by Conutik** [comment]
I do but i dont really understand some stuff so plz help

**Comment by Conutik** [comment]
Its easier if they just add .startsWith() back

**Comment by DaemonBeast** [comment]
You can get an array of the entries by using [`db.all()`](https://quickdb.js.org/overview/docs#all-method). Then you can filter and sort the results. You need to change the following line:

```js
let money = db.startsWith(`scores_${message.guild.id}`, { sort: '.data'})
```

to the following:

```js
let money = db.all().filter(entry => entry.ID.startsWith(`scores_${message.guild.id}`)).sort((a, b) => a.data < b.data);
```

I'm not sure if this will work with the rest of your code, so you may have to do some modifications.
