### ISSUE TITLE
Allow users to specify the database location.

### ISSUE THREAD

**Issue by tascord** [lorencerri/quick.db#171]
**Is your feature request related to a problem? Please describe.**
Running Discord bots, for example, require that you run said bot from the same folder each time. If you were to run it from your home directory for example, a new json.sqlite file would be created there, and the bot would read an empty database. Not only can this be extremely frustrating trying to debug things from within other folders, but makes CLI applications using quick.db completely unusable.

**Describe the solution you'd like**
I'd like to have the ability to specify an absolute path in the require method.

**Describe alternatives you've considered**
I've only considered switching to a more 'proper' database tool, however for small projects, this is an amazing time saver and I'd love to continue using it.

**Additional context**
N/a

**Comment by Androz2091** [comment]
I made a fork a year ago with a new method that could help you:
```js
const quickdb = require("quick.db");
quickdb.init("./custom-file.sqlite");
// quick.db methods will use the custom-file.sqlite file
```

**Comment by tascord** [comment]
> I made a fork a year ago with a new method that could help you:
> 
> ```js
> const quickdb = require("quick.db");
> quickdb.init("./custom-file.sqlite");
> // quick.db methods will use the custom-file.sqlite file
> ```
> 
> https://github.com/Androz2091/quick.db

Thanks, I'll be sure to use that! Still think this should be in the main stream due to all the issues it can create as is.

**Comment by GeekCornerGH** [comment]
I created the pull request (#194)
