### ISSUE TITLE
.push doesn't create an array when a string only contains numbers, instead it converts the string to a number

### ISSUE THREAD

**Issue by Nico105** [lorencerri/quick.db#173]
**Describe the bug**
Pushing a string that only contains numbers (ex: "12345) with `.push` will not create a array, instead it will convert the string to a number, setting the value of the db to an array before won't fix it either.

**To Reproduce**
```
db.push('test', '123434324234')
console.log(db.get('test'))
console.log(typeof db.get('test')) // number
```
or
```
db.set('test', [])
db.push('test', '123434324234')
console.log(db.get('test'))
console.log(typeof db.get('test')) // number
```

**Expected behavior**
It should create an array and push the string into it without converting it to a number.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/63612668/90686912-4d554280-e26c-11ea-922b-ffa821210db7.png)
![image](https://user-images.githubusercontent.com/63612668/90686952-63630300-e26c-11ea-8e06-0a8e533047ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - quick.db Version: 7.1.1

**Comment by lorencerri** [comment]
Unable to reproduce, if the issue persists with new test cases, please resubmit. Thank you!

**Comment by snapdeus** [comment]
I'm encountering this error.

in the below image, the result is an array with [0,1]
however, notice that i had to include a number in the array when i used db.set()
![image](https://user-images.githubusercontent.com/44621390/168194744-8975da1f-c767-4689-8f21-44fef94ec50f.png)

now, examine this image in which i use db.set() with an empty array and see the result:
![image](https://user-images.githubusercontent.com/44621390/168194921-26cd20aa-b566-41b5-8674-e324fdc67706.png)
the result is the number 1, not in array.

finally, if i remove the call to delete in this test function, and try to add another number, see the error result: TypeError: Target is not an array.
![image](https://user-images.githubusercontent.com/44621390/168195005-917d0faa-09a4-4d70-ae9a-4f3afc360b7a.png)
