### ISSUE TITLE
Quick.db not installing

### ISSUE THREAD

**Issue by MetalOoze05** [lorencerri/quick.db#177]
Whenever i try to install quick.db it never installes and shows this error

**I have also installed the windows build tools and followed all the steps on how to install**

error:
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ayan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ayan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Ayan\Desktop\Ayan Folders\ICS-Helper\node_modules\integer
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ayan\AppData\Roaming\npm-cache\_logs\2020-08-29T06_43_04_234Z-debug.log
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN enmap@5.7.1 requires a peer of better-sqlite3@^7.1.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ayan\AppData\Roaming\npm-cache\_logs\2020-08-29T06_43_06_836Z-debug.log

**Comment by phamleduy04** [comment]
open PowerShell with admin then `npm -g windows-build-tools`

**Comment by Purukitto** [comment]
> npm -g windows-build-tools

`npm i -g windows-build-tools`

**Comment by enffinity** [comment]
open powershell as administrator and type `npm -g --add-python-to-path install windows-build-tools node-gyp`

**Comment by lorencerri** [comment]
Closed due to inactivity
