### ISSUE TITLE
Cant install quick.db on Ubuntu 18 using pterodactyl panel

### ISSUE THREAD

**Issue by SaqibYT** [lorencerri/quick.db#182]
Hi, Ive been using quick.db on my pc for a while to store data in my bot. Ive recently bought a vps and installed pterodactyl to host my bot. It never installs so i try and adding the quickdb module in my `node_module` directory but then it says theres no better_sqlite3 even though its in node_modules. If you could please help me, thanks.

**Comment by WeebHiroyuki** [comment]
Hi. Can you state the error that's being returned?

**Comment by rhld16** [comment]
If you still have this error try `npm install better_sqlite3`

**Comment by lorencerri** [comment]
Closed due to inactivity
