### ISSUE TITLE
db.add not working

### ISSUE THREAD

**Issue by alide123321** [lorencerri/quick.db#187]
**Describe the bug**
Error: Data @ ID: "698051518754062300" IS NOT A number.

![Capture](https://user-images.githubusercontent.com/47161857/97696403-97ea0b00-1ab6-11eb-955d-de097fbfec08.PNG)
![Capture](https://user-images.githubusercontent.com/47161857/97696585-d7185c00-1ab6-11eb-8948-ff95a6d81518.PNG)

**Desktop (please complete the following information):**
 - OS: debian on repl.it server
 - Quick.db Version 7.1.3

**Comment by Snowflake107** [comment]
Looks like your existing data type is not a number

**Comment by lorencerri** [comment]
As described in the error message, it seems that whatever is stored at `${msg.author.id}.word_${argwords[n]}` isn't a number, but an object.
