### ISSUE TITLE
json.sqlite get created in wrong place

### ISSUE THREAD

**Issue by RobinSchapendonk** [lorencerri/quick.db#189]
**Describe the bug**
If you start a project outside the root dir, the database file gets created in the wrong place

**To Reproduce**
1. Go to your project's root directory (in the project's folder)
2. Do `cd ../`
3. Do `node <yourFolderName>`

**Expected behavior**
The database would be created in `<yourFolderName>/json.sqlite`.

**Screenshots**
[example of how it is](https://ss.pokehunt.xyz/qKRq)
[example how it should be](https://ss.pokehunt.xyz/TXlD)

**Desktop (please complete the following information):**
 - OS: Arch and Ubuntu (Linux)
 - Version 7.1.3

**Additional context**
I found this using pm2 because I always use pm2 outside of the root directory to start it, so I view the folder name in the pm2 list.

**Comment by RobinSchapendonk** [comment]
https://github.com/lorencerri/quick.db/blob/b7011af42001726cc9da1df4c40758b95c9e8321/src/index.js#L7
The problem is that `./` refers to the directory where the project is started in (I believe), which means it will create it in the folder you start the project with.

**Comment by rhld16** [comment]
This issue no longer occurs in the latest commit (probably since #202) yet it is yet to be pushed to npm
