### ISSUE TITLE
quick.db not installing with node.js

### ISSUE THREAD

**Issue by therealkingnull** [lorencerri/quick.db#192]
When trying to install quick.db running node.js v12, it produces many errors. I know that a lot of other people are having this issue, and it makes it impossible to use this package.

**Comment by biminkoju** [comment]
same

**Comment by chickenloveryt** [comment]
Same with me lol

**Comment by strikingwd** [comment]
same dude, i cant find any fix

**Comment by therealkingnull** [comment]
> same
> edit: i have sucessfully installed it

how?

**Comment by lorencerri** [comment]
Closed due to lack of information & inactivity, if the installation issue persists, please create a new one with an error log

**Comment by therealkingnull** [comment]
> Closed due to lack of information & inactivity, if the installation issue persists, please create a new one with an error log

so...you’re just closing this without providing any information to help me and everyone else who is trying to install your package??

**Comment by lorencerri** [comment]
> > Closed due to lack of information & inactivity, if the installation issue persists, please create a new one with an error log
> 
> 
> 
> so...you’re just closing this without providing any information to help me and everyone else who is trying to install your package??

You're free to create a new issue, although please provide error logs so we can try to help pinpoint what's going wrong & organize better
