### ISSUE TITLE
cannot download npm i quick.db

### ISSUE THREAD

**Issue by yoguys** [lorencerri/quick.db#200]
i cannot download npm i quick.db error that i get

C:\WINDOWS\system32>npm i quick.db

> better-sqlite3@7.1.2 install C:\WINDOWS\system32\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=15.5.1 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.2 build-release C:\WINDOWS\system32\node_modules\better-sqlite3
> node-gyp rebuild --release

C:\WINDOWS\system32\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\usr\local\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\usr\local\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\usr\\local\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\better-sqlite3
gyp ERR! node -v v15.5.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! better-sqlite3@7.1.2 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abdul\AppData\Roaming\npm-cache\_logs\2021-01-10T11_32_52_749Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abdul\AppData\Roaming\npm-cache\_logs\2021-01-10T11_32_53_198Z-debug.log

**Comment by nicocarr04** [comment]
That a pretty easy fix just do: npm install -g windows-build-tools
if you already did it try reinstalling node.js

**Comment by yoguys** [comment]
still not working

**Comment by Zorotic** [comment]
Follow this: 

NOTE: REQUIRES NODE V8
**Stuff before installation:**
```
- You can use CMD like the Powershell to do those steps there is not a specific terminal to use
 
- Node-gyp needs python 2.x or 3.x and Visual C++ Build Tools.
 
- If you are on windows vista / 7 you will need to install the .NET Framework 4.5.1 which can be downloaded here:
  https://www.microsoft.com/en-us/download/details.aspx?id=40773
```

1- Click on the windows-key of your keyboard to open the windows menu

2- Type cmd/powershell (It's totally your choice) and right click on the first result

3- Click "Run as Administrator"

4- When the terminal is opened type npm install --global windows-build-tools --vs2015 in it and the installation will start. (Sometimes this can take long)

5- When the installation is finished you can close the terminal.

6- Now you must go to the directory where you want to install Quick.db.

7- Hold Left-Shift and right click on a blank space of the directory.

8- Click on "Open PowerShell window here".

9- If you see a file named "package.json" in your folder skip to 11

10- Type "npm init -y" in the terminal

11- Type npm i quick.db
