### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Ult1m1** [lorencerri/quick.db#201]
ERROR: https://sourceb.in/1c7aNeepCP
Windows 10

"quick.db": "^7.1.3",
"discord.js": "github:discordjs/discord.js",

node v14 (I got an error after updating the node)

**Comment by haroongames-git** [comment]
The error is coming from `node_modules/bindings`, not `node_modules/quick.db`. Therefore, this is not a quick.db error. Try contact the owner of the `bindings` package.
