### ISSUE TITLE
Concurrency? 

### ISSUE THREAD

**Issue by BasToTheMax** [lorencerri/quick.db#212]
What happens when I try to set multiple keys at the same time?

Will it corrupt my data?

**Comment by Loom4k** [comment]
I wouldn’t reccomend changing a lot of data in the same file at the same time. You could prevent data corruption by using async/await functions.

**Comment by BasToTheMax** [comment]
Ok. Thx for your response :)

**Comment by Loom4k** [comment]
No problem! I used to use quick.db too when I was working on small discord bots. If you are doing on a bigger project or even a website/app, I would definitely recommend using a better database system such as mongoDb/mongoose or an actual Sqlite database. Hope this helps, loom4k
