### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by falseCloud** [lorencerri/quick.db#213]
Hey, is this possible to install quick.db on android?

**Comment by AlmondPark** [comment]
all you can do is create files in explorer and copy the code from the folder in this repository src /

**Comment by AlmondPark** [comment]
Just write in your android terminal: cd [folder path] => git init => git remote https://github.com/lorencerri/quick.db => git clone https://github.com/lorencerri/quick.db [folder name to clone in it] then go to src and copy files to your node modules folder

**Comment by AlmondPark** [comment]
https://github.com/AlmondPark/node_modules/blob/main/modules_links.md

**Comment by falseCloud** [comment]
thanks!

**Comment by AlmondPark** [comment]
Np
